// Maps FontAwesome icon names to Lucide Vue components
import {
  AlertCircle, AlertTriangle, ArrowLeftRight, Banknote, Bell, BookMarked,
  BookOpen, BookUser, Bookmark, BugOff, Building2, CalendarCheck, ChevronDown,
  ChevronUp, CircleX, ClipboardList, CloudCheck, CloudDownload, CloudUpload,
  Code, Copy, CreditCard, Download, ExternalLink, FileCode, FileSpreadsheet,
  FileText, FileX2, FlaskConical, FolderOpen, Ghost, GitBranch, HandCoins,
  Handshake, HardDrive, Headset, Info, KeyRound, Laptop, Layers, Lightbulb,
  Link, ListChecks, Megaphone, Monitor, Moon, Network, Pencil, Phone, Pill,
  Power, Receipt, RotateCw, Search, Server, Settings, ShieldCheck, SlidersHorizontal,
  Smartphone, StickyNote, Store, Sun, Target, Ticket, ToggleLeft, Toolbox,
  Trash2, User, UserCog, UserLock, UserMinus, Users, Wrench, Zap, X, Mail, Calendar,
  PenSquare, Check, Clock
} from '@lucide/vue'

export const iconMap = {
  'fa-address-book':              BookUser,
  'fa-arrow-up-right-from-square':ExternalLink,
  'fa-bell':                      Bell,
  'fa-book-bookmark':             BookMarked,
  'fa-book-open':                 BookOpen,
  'fa-bookmark':                  Bookmark,
  'fa-bolt':                      Zap,
  'fa-bug-slash':                 BugOff,
  'fa-building-user':             Building2,
  'fa-bullhorn':                  Megaphone,
  'fa-bullseye':                  Target,
  'fa-calendar':                  Calendar,
  'fa-calendar-check':            CalendarCheck,
  'fa-cc-discover':               CreditCard,
  'fa-check':                     Check,
  'fa-chevron-down':              ChevronDown,
  'fa-chevron-up':                ChevronUp,
  'fa-circle-exclamation':        AlertCircle,
  'fa-circle-info':               Info,
  'fa-circle-nodes':              Network,
  'fa-circle-xmark':              CircleX,
  'fa-clipboard-list':            ClipboardList,
  'fa-clock':                     Clock,
  'fa-cloud-arrow-down':          CloudDownload,
  'fa-cloud-arrow-up':            CloudUpload,
  'fa-cloud-check':               CloudCheck,
  'fa-code':                      Code,
  'fa-code-branch':               GitBranch,
  'fa-copy':                      Copy,
  'fa-credit-card':               CreditCard,
  'fa-desktop':                   Monitor,
  'fa-download':                  Download,
  'fa-envelope':                  Mail,
  'fa-external-link-alt':         ExternalLink,
  'fa-file-circle-xmark':         FileX2,
  'fa-file-code':                 FileCode,
  'fa-file-excel':                FileSpreadsheet,
  'fa-file-invoice':              Receipt,
  'fa-file-invoice-dollar':       Receipt,
  'fa-file-shield':               ShieldCheck,
  'fa-flask':                     FlaskConical,
  'fa-folder-open':               FolderOpen,
  'fa-gears':                     Settings,
  'fa-ghost':                     Ghost,
  'fa-google-drive':              HardDrive,
  'fa-hand-holding-dollar':       HandCoins,
  'fa-handshake':                 Handshake,
  'fa-headset':                   Headset,
  'fa-key':                       KeyRound,
  'fa-laptop-file':               Laptop,
  'fa-layer-group':               Layers,
  'fa-lightbulb':                 Lightbulb,
  'fa-link':                      Link,
  'fa-list-check':                ListChecks,
  'fa-magnifying-glass':          Search,
  'fa-money-bill-transfer':       ArrowLeftRight,
  'fa-money-check-dollar':        Banknote,
  'fa-moon':                      Moon,
  'fa-network-wired':             Network,
  'fa-note-sticky':               StickyNote,
  'fa-pen-to-square':             PenSquare,
  'fa-pencil':                    Pencil,
  'fa-phone':                     Phone,
  'fa-power-off':                 Power,
  'fa-prescription-bottle-medical': Pill,
  'fa-rotate':                    RotateCw,
  'fa-screwdriver-wrench':        Wrench,
  'fa-search':                    Search,
  'fa-server':                    Server,
  'fa-sliders':                   SlidersHorizontal,
  'fa-store':                     Store,
  'fa-sun':                       Sun,
  'fa-ticket':                    Ticket,
  'fa-times':                     X,
  'fa-toggle-off':                ToggleLeft,
  'fa-toolbox':                   Toolbox,
  'fa-trash-can':                 Trash2,
  'fa-triangle-exclamation':      AlertTriangle,
  'fa-user':                      User,
  'fa-user-lock':                 UserLock,
  'fa-user-minus':                UserMinus,
  'fa-users':                     Users,
  'fa-users-gear':                UserCog,
  'fa-wrench':                    Wrench,
}
